### ISSUE TITLE
Crashes in searches for GNOME 42

### ISSUE THREAD

**Issue by pabloyoyoista** [Cogitri/gnome-software-plugin-apk#49]
GNOME 42 crashes during searches with a backtrace I cannot decipher
```
#0  magazine_chain_pop_head (magazine_chunks=magazine_chunks@entry=0x7fffeef097d0) at ../glib/gslice.c:583
#1  0x00007ffff7bc2e06 in thread_memory_magazine1_alloc (ix=<optimized out>, tmem=0x7fffeef097c0) at ../glib/gslice.c:886
#2  g_slice_alloc (mem_size=mem_size@entry=16) at ../glib/gslice.c:1063
#3  0x00007ffff7c8d2ca in g_object_notify_queue_freeze (object=object@entry=0x7fffeef780c0 [GTask], conditional=conditional@entry=0) at ../gobject/gobject.c:294
#4  0x00007ffff7c8e3df in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3632
#5  g_object_unref (_object=0x7fffeef780c0) at ../gobject/gobject.c:3553
#6  0x00007ffff7bab7a4 in g_source_callback_unref (cb_data=0x7fffeeff0920) at ../glib/gmain.c:1702
#7  g_source_callback_unref (cb_data=0x7fffeeff0920) at ../glib/gmain.c:1695
#8  0x00007ffff7babba6 in g_source_destroy_internal (source=source@entry=0x7ffff1351960, context=context@entry=0x7ffff1ba83d0, have_lock=have_lock@entry=1) at ../glib/gmain.c:1367
#9  0x00007ffff7bae096 in g_main_dispatch (context=0x7ffff1ba83d0) at ../glib/gmain.c:3447
#10 g_main_context_dispatch (context=context@entry=0x7ffff1ba83d0) at ../glib/gmain.c:4135
#11 0x00007ffff7bae26e in g_main_context_iterate (context=context@entry=0x7ffff1ba83d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4211
#12 0x00007ffff7bae320 in g_main_context_iteration (context=0x7ffff1ba83d0, may_block=1) at ../glib/gmain.c:4276
#13 0x00007ffff7f3ae0a in  () at /usr/lib/gnome-software/libgnomesoftware.so.18
#14 0x00007ffff7d66f0b in g_task_thread_pool_thread (thread_data=0x7fffef48a0c0, pool_data=<optimized out>) at ../gio/gtask.c:1452
#15 0x00007ffff7bcc79b in g_thread_pool_thread_proxy (data=<optimized out>) at ../glib/gthreadpool.c:354
#16 0x00007ffff7bcc100 in g_thread_proxy (data=0x7ffff1c98800) at ../glib/gthread.c:827
#17 0x00007ffff7fba1f5 in start (p=0x7ffff18d85e0) at src/thread/pthread_create.c:203
#18 0x00007ffff7fbc470 in __clone () at src/thread/x86_64/clone.s:22
```

Will have to ask upstream...

**Comment by pabloyoyoista** [comment]
Took a while, but reported it: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1833
